server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/aelbihi_workshops
    driver-class-name: org.postgresql.Driver
    username: aelbihi
    password: 147896325

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
          format-sql: true
          database: postgresql
#          database-platform: org.hibernate.dialect.PostgresSQLDialect


